---
- name: add nodesource repo
  shell: curl -sL https://deb.nodesource.com/setup | sudo -E bash -

- name: add docker gpg key (Debian)
  become: yes
  shell: apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  when: ansible_distribution == 'Debian'

- name: add docker repository (Debian)
  become: yes
  shell: echo deb https://apt.dockerproject.org/repo debian-stretch main > /etc/apt/sources.list.d/docker.list
  when: ansible_distribution == 'Debian'

- name: update apt
  become: yes
  apt: update_cache=yes

- name: install libraries with apt (Debian)
  become: yes
  apt: name={{ item }} state=latest
  with_items: debian_libraries
  when: ansible_distribution == 'Debian'

- name: install libraries with apt
  become: yes
  apt: name={{ item }} state=latest
  with_items: linux_libraries
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install npm packages
  become: yes
  npm: global=yes name={{ item }}
  with_items: npm_packages
