---
- name: add nodesource repo
  shell: curl -sL https://deb.nodesource.com/setup | sudo -E bash -

- name: update apt
  become: yes
  apt: update_cache=yes

- name: install Debian specific libraries
  become: yes
  apt: name={{ item }} state=latest
  with_items: debian_libraries
  when: ansible_distribution == 'Debian'

- name: install libraries with apt
  become: yes
  apt: name={{ item }} state=latest
  with_items: linux_libraries
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install npm packages
  become: yes
  npm: global=yes name={{ item }}
  with_items: npm_packages
