---
# Version validation for when v2 is avaliable via package managers
# - name: validate ansible version
#   run_once: true
#   debug: msg="You need at least ansible 2.0, currently using {{ ansible_version.full }}"
#   failed_when: "{{ ansible_version.full | version_compare('2.0', operator='lt', strict=True)}}"

- name: create system groups
  group_by:
    key: "sys_{{ ansible_system }}"
  changed_when: false
