---
- name: composer self-update
  shell: composer self-update

- name: composer install
  composer:
    # command: install (only avaliable in Ansible 1.8)
    no_dev: yes
    working_dir: "{{ deploy_release.path }}/bedrock"

- name: npm install
  npm:
    path: "{{ deploy_release.path }}/bedrock"

- name: bower install
  shell: "cd {{ deploy_release.path }}/bedrock && bower install --config.interactive=false"

- name: bower install codepool
  shell: "cd {{ deploy_release.path }}/bedrock/web/app/mwn-codepool && bower install --config.interactive=false"

- name: run grunt
  shell: "cd {{ deploy_release.path }}/bedrock && grunt"

- name: get docker IP
  action: docker_ip # This returns the varible `docker_ip`
  changed_when: false

- name: update /etc/hosts
  sudo: yes
  shell: "{{ item }}"
  with_items:
   - "{{ bin_dir }}/etchosts update web {{ docker_ip }}"
   - "{{ bin_dir }}/etchosts update database {{ docker_ip }}"
   - "{{ bin_dir }}/etchosts update {{ site_name }}.dev {{ docker_ip }}" # add www and non www
   - "{{ bin_dir }}/etchosts update www.{{ site_name }}.dev {{ docker_ip }}"
