---
- name: docker-machine create
  shell: "docker-machine create --driver virtualbox dev"

- name: docker-machine start
  shell: "docker-machine start dev"

- name: set environment variables that the Docker client will read which specify the TLS settings
  shell: "eval $(docker-machine env dev)"
