---
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/tmp
  args:
    creates: /usr/local/bin/composer

- name: rename composer.phar to composer
  sudo: yes
  shell: mv /tmp/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: make composer executable
  sudo: yes
  file:
    path: /usr/local/bin/composer
    mode: 0755
    state: file

- name: install wp-cli
  shell: curl --output /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  args:
    creates: /usr/local/bin/wp

- name: make wp-cli executable
  sudo: yes
  file:
    path: /usr/local/bin/wp
    mode: 0755
    state: file

- name: install sass
  gem:
    name: sass
    state: present

- name: install pip
  sudo: yes
  easy_install:
    name: pip
    # state: latest <-- ansible v2 only

- name: install mysql-python # for adding db with Ansible
  sudo: yes
  pip:
    name: MySQL-python
    state: present
