---
- name: detect shell
  action: detect_shell # This returns the varibles `detected_shell` and `shellrc_dir`
  changed_when: false

- name: add workwork bin to PATH in .bashrc or .zshrc
  lineinfile:
    dest: "{{ shellrc_dir }}"
    regexp: "workwork bin path"
    line: "export PATH=$PATH:{{ bin_dir }} # workwork bin path (added with workstation.yml)"
    create: yes
    state: present

- name: add workwork bin to PATH in .bash_profile
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    regexp: "workwork bin path"
    line: "export PATH=$PATH:{{ bin_dir }} # workwork bin path (added with workstation.yml)"
    create: yes
    state: present
  when: detected_shell == "bash"

- name: add execute to files in workwork bin
  file:
    path: "{{ bin_dir }}"
    mode: 0755
    recurse: yes

- name: add boot2docker shellinit .bashrc or .zshrc
  lineinfile:
    dest: "{{ shellrc_dir }}"
    regexp: "workwork boot2docker"
    line: "if [ $(type -P boot2docker) ]; then eval $(boot2docker shellinit); fi # workwork boot2docker (added with workstation.yml)"
    create: yes
    state: present
  when: ansible_distribution == "MacOSX"

- name: add boot2docker shellinit .bash_profile
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    regexp: "workwork boot2docker"
    line: "if [ $(type -P boot2docker) ]; then eval $(boot2docker shellinit); fi # workwork boot2docker (added with workstation.yml)"
    create: yes
    state: present
  when: ansible_distribution == "MacOSX" and detected_shell == "bash"
