#!/bin/bash

# Output fancy titles
display_status_primary() {
  STATUS=$1
  MESSAGE=$2
  PRIMARY_COLOUR="COLOUR"_"${STATUS}"
  echo -e "${!PRIMARY_COLOUR}"
  echo "${MESSAGE}"
  echo "--------------------------------------------------------"
  echo -e "${COLOUR_RESET}"
}

# Output status messages
display_status_secondary() {
  STATUS=$1
  MESSAGE=$2
  SECONDARY_COLOUR="COLOUR"_"${STATUS}"
  SECONDARY_SYMBOL="SYMBOL"_"${STATUS}"
  echo -e "${!SECONDARY_COLOUR}${!SECONDARY_SYMBOL}${COLOUR_RESET} ${MESSAGE}"
  if [ $STATUS == "ERROR" ]; then
    exit 1
  fi
}

# Output shared version
display_version() {
  echo "mwn-workwork ${VER_LOCAL}"
  exit 1
}

# Output shared arguments
display_arguments() {
  echo "Arguments:"
  echo "   dd         Debrief Daily"
  echo "   mm         Mamamia (coming soon)"
  echo "   iv         iVillage (coming soon)"
  echo "   tg         The Glow (coming soon)"
  echo "   rh         Random Harry (coming soon)"
  exit 1
}

display_ww_usage() {
  echo "Usage: ww [--workstation] [--version] [--help] <command> [args] [--local]"
  echo
}

display_ww_commands() {
  echo "Commands:"
  echo "   init       Initialise local development environment"
  echo "   start      Start local development environment"
  echo "   stop       Stop local development environment"
  echo "   update     Run git pull and composer update"
  echo "   updatedb   Overwrite local database with current production tables"
  echo
}

display_ww_help() {
  display_ww_usage
  display_ww_commands
  display_arguments
}
