#!/bin/bash

run_ansible_playbook_init() {
  print_status_secondary "INFO" "[ Running ansible-playbook... ]"
  ansible-playbook \
  --ask-sudo-pass \
  "${WW_DIR}/ansible/init.yml" \
  -i "${WW_DIR}/ansible/inventory/hosts" \
  -e "site_dir=${SITE_DIR}" \
  -e "site_name=${SITE_NAME}"
}