#!/bin/bash

run_command_init() {
  print_status_primary "INFO" "Initialise ${SITE_FULL_NAME}"
  util_ansible_playbook "${WW_DIR}" "init.yml"
  util_ansible_playbook "${WW_DIR}" "start.yml"
  util_ansible_playbook "${SITE_DIR}" "start.yml"
  util_ansible_playbook "${WW_DIR}" "init-postclone.yml"
  print_status_secondary "PASS" "Completed all tasks!"
}

run_command_start() {
  print_status_primary "INFO" "Start ${SITE_FULL_NAME}"
  util_ansible_playbook "${WW_DIR}" "kill.yml"
  util_ansible_playbook "${WW_DIR}" "start.yml"
  util_ansible_playbook "${SITE_DIR}" "start.yml"
  util_grunt_watch
  print_status_secondary "PASS" "Completed all tasks!"
}

run_command_watch() {
  print_status_primary "INFO" "Watch ${SITE_FULL_NAME}"
  util_ansible_playbook "${WW_DIR}" "kill.yml" --extra-vars="kill_process=grunt"
  util_grunt_watch
  print_status_secondary "PASS" "Completed all tasks!"
}

run_command_stop() {
  print_status_primary "INFO" "Stop ${SITE_FULL_NAME}"
  util_ansible_playbook "${WW_DIR}" "stop.yml"
  print_status_secondary "PASS" "Completed all tasks!"
}

run_command_rm() {
  print_status_primary "INFO" "Remove ${SITE_FULL_NAME}"
  util_ansible_playbook "${WW_DIR}" "rm.yml"
  print_status_secondary "PASS" "See you Space Cowboy!"
}

run_argument_update() {
  print_status_primary "INFO" "Update workwork"
  util_update_workwork
}

run_argument_install() {
  print_status_primary "INFO" "Install workwork"
  util_ansible_playbook "${WW_DIR}" "install.yml" "--ask-become-pass ${1}"
  print_status_secondary "PASS" "Completed all tasks!"
}

run_argument_clean() {
  print_status_primary "INFO" "Remove legacy changes to system"
  util_ansible_playbook "${WW_DIR}" "clean.yml" "--ask-become-pass"
  print_status_secondary "PASS" "Completed all tasks!"
}

run_argument_version() {
  util_git_fetch
  print_version
}

run_argument_help() {
  print_help
}
