#!/bin/bash

run_workstation() {
  display_status_primary "INFO" "Updating workstation"
  run_ansible_playbook_workstation
  display_status_secondary "PASS" "Completed all tasks!"
}

run_init() {
  display_status_primary "INFO" "Running init for ${SITE_FULL_NAME}"
  check_sudo
  check_clone_app
  post_clone
  init_boot2docker
  update_etchosts
  run_ansible_playbook_init
  display_status_secondary "PASS" "Completed all tasks!"
  # Reset the shell to export new docker envvars into our shell
  source $PROFILE
  exec $DETECTED_SHELL
}

run_start() {
  display_status_primary "INFO" "Running start for ${SITE_FULL_NAME}"
  grunt_watch
  docker_compose
  display_status_secondary "PASS" "Completed all tasks!"
}

run_update() {
  display_status_primary "INFO" "Running update for ${SITE_FULL_NAME}"
  update_git
  display_status_secondary "PASS" "Completed all tasks!"
}

run_updatedb() {
  display_status_primary "INFO" "Running updatedb for ${SITE_FULL_NAME}"
  check_sudo
  update_db
  display_status_secondary "PASS" "Completed all tasks!"
}
