#!/bin/bash

# Run commands in the background
# Credit: http://stackoverflow.com/a/15578203

grunt_watch() {
  cd ${SITE_DIR}/bedrock && grunt watch &
}

docker_compose() {
  if [ $PLATFORM == "osx" ]; then
    boot2docker up 2>/dev/null
    cd ${SITE_DIR}/docker && docker-compose up &
  else
    cd ${SITE_DIR}/docker && sudo docker-compose up &
  fi
}
