#!/bin/bash

stop_docker() {
  # stop only per-site container
  print_status_primary "INFO" "Stopping mwn-${SITE_NAME}..."
  docker stop mwn-${SITE_NAME}
}

kill_docker_containers() {
  # stop and remove all containers listed
  DOCKER_CONTAINERS=${1}
  print_status_primary "INFO" "Stopping containers..."
  docker stop ${DOCKER_CONTAINERS}
  print_status_primary "INFO" "Removing containers..."
  docker rm ${DOCKER_CONTAINERS}
}
