#!/bin/bash

update_db() {
  # Check user error status credit: http://stackoverflow.com/a/12137501
  mkdir -p ${SITE_DIR}/bedrock/db-sync/
  
  # Download update or manual upload file
  if (($IS_LOCAL == 0)); then
    source ${SITE_DIR}/secret/mysql/readonly
    gunzip ${SITE_DIR}/bedrock/db-sync/wordpress.sql.gz
  else
    # if no DB file, exit
    if [ ! -f ${SITE_DIR}/bedrock/db-sync/wordpress.sql ]; then
      display_status_secondary "ERROR" "No wordpress.sql file found under ${SITE_DIR}/bedrock/db-sync/, upload file or remove --local"
      exit
    fi
  fi
  ${SITE_DIR}/bedrock/vendor/wp-cli/wp-cli/bin/wp --path=${SITE_DIR}/bedrock/web/wp db import ${SITE_DIR}/bedrock/db-sync/wordpress.sql
  ${SITE_DIR}/bedrock/vendor/wp-cli/wp-cli/bin/wp --path=${SITE_DIR}/bedrock/web/wp search-replace --recurse-objects ${SITE_PROD_URL} www.${SITE_NAME}.dev
  CHECK_USER=$(${SITE_DIR}/bedrock/vendor/wp-cli/wp-cli/bin/wp --path=${SITE_DIR}/bedrock/web/wp user get dev)
  if [[ $? != 0 ]]; then
    ${SITE_DIR}/bedrock/vendor/wp-cli/wp-cli/bin/wp --path=${SITE_DIR}/bedrock/web/wp user create dev dev@mwnstack.com --role=administrator --user_pass=dev
  fi
  ${SITE_DIR}/bedrock/vendor/wp-cli/wp-cli/bin/wp --path=${SITE_DIR}/bedrock/web/wp plugin activate --all
  ${SITE_DIR}/bedrock/vendor/wp-cli/wp-cli/bin/wp --path=${SITE_DIR}/bedrock/web/wp theme activate ${SITE_NAME}
}
