#!/bin/bash

# Utility functions
type_exists() {
  if [ $(type -P $1) ]; then
    return 0
  fi
  return 1
}

# Compares git hashes
check_version() {
  cd $WW_DIR && git fetch
  if [ $VER_LOCAL = $VER_REMOTE ]; then
    :
  elif [ $VER_LOCAL = $VER_BASE ]; then
    display_status_primary "INFO" "Updating WorkWork..."
    cd $WW_DIR && git pull -q origin master
  elif [ $VER_REMOTE = $VER_BASE ]; then
    display_status_primary "WARN" "Please push your changes to the remote..."
  else
    display_status_primary "WARN" "Can't update due to local changes..."
  fi
}

# Ensure at least one command is supplied
check_command() {
  if [ $1 -lt 1 ]; then
    $0 "--help"
  fi
}

setup_site() {
  if [ $1 = "dd" ]; then
    SITE_NAME="debriefdaily"
    SITE_DIR="${HOME}/workspace/mwn-${SITE_NAME}"
    SITE_PROD_URL="www.${SITE_NAME}.com"
  # elif [ $1 = "mm" ]; then
  #   # Etc
  fi
}

# Detect shell
# http://stackoverflow.com/questions/9910966/how-to-tell-if-its-using-zsh-or-bash
check_shell() {
  if [ -n "`$SHELL -c 'echo $ZSH_VERSION'`" ]; then
    DETECTED_SHELL="zsh"
    PROFILE="${HOME}/.zshrc"
  elif [ -n "`$SHELL -c 'echo $BASH_VERSION'`" ]; then
    DETECTED_SHELL="bash"
    PROFILE="${HOME}/.bash_profile"
  else
    echo "FATAL: Could not detect the shell!"
    exit
  fi
}

# Detect the platform via uname
# http://stackoverflow.com/a/17072017
# https://raw.githubusercontent.com/yellowducklabs/duckos/master/duck
check_platform() {
  if [[ "$UNAME" == 'Darwin' ]]; then
    PLATFORM="osx"
  elif [[ "$UNAME" == 'Linux' ]]; then
    PLATFORM="linux"
  elif [[ "$UNAME" == 'MINGW32_NT' ]]; then
    echo -e "FATAL: This script is not Windows compatible.\nThat, my friend, is up to you now.\n\nGood luck!"
    exit
  else
    echo "FATAL: Could not detect the platform!"
    exit
  fi
}
