#!/bin/bash

# Commands
VALID_COMMANDS="@(init|start|update|updatedb|stop)"

# Arguments
VALID_ARGUMENTS="@(dd|mm|iv|tg|rh|tm)"
INVALID_ARGUMENTS="@(''|*)"

# Locak flag
IS_LOCAL=0

# Platform
UNAME=`uname`
PLATFORM="unknown"

# Set colours
COLOUR_ESC="\033["
COLOUR_ERROR="${COLOUR_ESC}31m"
COLOUR_PASS="${COLOUR_ESC}32m"
COLOUR_WARN="${COLOUR_ESC}33m"
COLOUR_INFO="${COLOUR_ESC}34m"
COLOUR_RESET="${COLOUR_ESC}0m"

# Set symbols
SYMBOL_ERROR="x"
SYMBOL_PASS="✓"
SYMBOL_WARN="!"
SYMBOL_INFO="*"
