#!/bin/bash

run_ansible_playbook() {
  display_status_secondary "INFO" "[ Running ansible-playbook... ]"
  ansible-playbook "${WW_DIR}/ansible/workstation.yml" -i "${WW_DIR}/ansible/hosts" --ask-sudo-pass
}
