---
- hosts: workstation
  connection: local

  roles:
    - define_system

# Global
- hosts: workstation
  connection: local
  tasks:
    # Create facts `detected_shell` and `shellrc_dir`
    - name: detect shell
      action: detect_shell
      changed_when: false

    # Clean up legacy stuff
    - name: remove legacy changes to $PATH in .bashrc or .zshrc
      lineinfile:
        dest: "{{ shellrc_dir }}"
        regexp: "workspace/mwn-workwork/bin"
        state: absent

    - name: remove legacy changes to $PATH in .bash_profile
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.bash_profile"
        regexp: "workspace/mwn-workwork/bin"
        state: absent
      when: detected_shell == "bash"

    - name: remove legacy changes to sudoers file
      become: yes
      lineinfile:
        dest: /etc/sudoers
        state: absent
        regexp: '%ADMIN ALL=\(ALL\) NOPASSWD:ALL'
        validate: "visudo -cf %s"
      changed_when: false
