---
- hosts: workstation
  connection: local
  roles:
    - define_system

# Global
- hosts: workstation
  connection: local
  gather_facts: false
  tasks:
    - name: register deploy path
      file:
        path: "{{ site_dir }}"
        state: directory
      register: deploy_release

    - name: git clone
      git:
        repo: "git@github.com:mamamia/mwn-{{ site_name }}"
        version: master
        accept_hostkey: yes
        dest: "{{ deploy_release.path }}"
        update: no

    # TEMP
    - name: git clone beanstalk (temp)
      git:
        repo: "git@mamamia.git.beanstalkapp.com:/mamamia/mamamia.git"
        version: master
        accept_hostkey: yes
        dest: "{{ deploy_release.path }}/bedrock"
        update: no
        version: prod
      when: site_name == "mamamia"
    # /TEMP

    # TEMP
    - name: git clone beanstalk (temp)
      git:
        repo: "git@mamamia.git.beanstalkapp.com:/mamamia/the-glow.git"
        version: master
        accept_hostkey: yes
        dest: "{{ deploy_release.path }}/bedrock"
        update: no
        version: prod
      when: site_name == "theglow"
    # /TEMP

    - name: setup env
      template:
        src: templates/env.j2
        dest: "{{ deploy_release.path }}/bedrock/.env"
        mode: 0744
