---
- hosts: workstation
  connection: local
  roles:
    - define_system

# OS X
- hosts: sys_Darwin
  connection: local
  gather_facts: false
  roles:
    - init_darwin_tasks

# Global
- hosts: workstation
  connection: local
  gather_facts: false
  roles:
    - init_clone
    - init_post_clone
    - init_define_env