---
- hosts: workstation
  connection: local

  roles:
    - define_system

# Global
- hosts: workstation
  connection: local
  gather_facts: false
  tasks:
    - name: register deploy path
      file:
        path: "{{ site_dir }}"
        state: directory
      register: deploy_release

    - name: git clone
      git:
        repo: "git@github.com:mamamia/{{ site_name }}"
        version: master
        accept_hostkey: yes
        dest: "{{ deploy_release.path }}"
        update: no

    - debug: msg="{{ site_name }}"

    - name: setup env
      template:
        src: templates/env.j2
        dest: "{{ deploy_release.path }}/bedrock/.env"
        mode: 0744
