---
- hosts: workstation
  connection: local

  roles:
    - define_system

  tasks:
    - name: "removing docker container"
      docker:
        image: mamamia/nginx-phpfpm
        name: "mwn-{{ site_name }}"
        state: absent
        use_tls: "{{ docker_tls }}"
