---
- hosts: workstation
  connection: local

  roles:
    - define_system

- hosts: workstation
  connection: local
  tasks:
    # Repo: https://github.com/docker-library/mysql
    # Docs: https://github.com/docker-library/docs/tree/master/mysql
    - name: start mwn-mysql-data (once)
      docker:
        image: mysql:5.6
        name: mwn-mysql-data
        volumes:
          #- /mnt/sda1/var/lib/mysql
          - /Volume/var/lib/mysql
        state: present
        use_tls: "{{ docker_tls }}"

    - name: start mwn-mysql
      docker:
        image: mysql:5.6
        name: mwn-mysql
        env:
          MYSQL_ROOT_PASSWORD: root
        volumes_from:
          - mwn-mysql-data
        volumes:
          - /Volume/var/lib/mysql:/var/lib/mysql
          - "{{ ansible_env.HOME }}/workspace/mwn-workwork/config/mysql:/etc/mysql/conf.d"
        ports:
          - "3306:3306"
        use_tls: "{{ docker_tls }}"

