---
- hosts: workstation
  connection: local

  roles:
    - define_system

  tasks:
    - name: "stopping docker container"
      docker:
        image: mamamia/nginx-phpfpm
        name: "mwn-{{ site_name }}"
        state: stopped
        use_tls: "{{ docker_tls }}"
