---
- hosts: workstation

  vars:
    linux_libraries:
      - git-core
      - ruby-full
      - nodejs
      - docker.io
    debian_libraries:
      - php5
      - php5-curl
    osx_libraries:
      - git
      - node
      - brew-cask
    osx_taps:
      - caskroom/cask
    osx_casks:
      - boot2docker
    npm_packages:
      - grunt-cli
      - grunt
      - bower

  tasks:
    # Debian only
    - name: Install Debian specific libraries
      sudo: yes
      apt: name=curl state=latest
      when: ansible_distribution == 'Debian'

    # Linux only
    - name: Add nodesource repo
      shell: curl -sL https://deb.nodesource.com/setup | sudo bash -
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Update apt
      sudo: yes
      apt: update_cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    # Debian only
    - name: Install Debian specific libraries
      sudo: yes
      apt: name={{ item }} state=latest
      with_items: debian_libraries
      when: ansible_distribution == 'Debian'

    - name: Install libraries with apt
      sudo: yes
      apt: name={{ item }} state=latest
      with_items: linux_libraries
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install libraries with yum
      sudo: yes
      yum: name={{ item }} state=latest
      with_items: linux_libraries
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    # OS X only
    - name: Update homebrew
      homebrew: update_homebrew=yes
      when: ansible_distribution == 'MacOSX'

    - name: Install homebrew taps
      homebrew_tap: name={{ item }} state=present
      with_items: osx_taps
      when: ansible_distribution == 'MacOSX'

    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items: osx_libraries
      when: ansible_distribution == 'MacOSX'

    - name: Check for installed casks
      shell: brew cask list | grep {{ item }}
      register: installed_casks
      with_items: osx_casks
      changed_when: false
      when: ansible_distribution == 'MacOSX'

    - name: Install missing casks
      shell: brew cask install {{ item }}
      with_items: osx_casks
      when: ansible_distribution == 'MacOSX' and item not in installed_casks.results|map(attribute='stdout')

    # All systems
    - name: Install composer
      shell: curl -sS https://getcomposer.org/installer | sudo php && sudo mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

    - name: Install Sass
      gem: name=sass state=present

    - name: Install npm packages globally
      npm: global=yes name={{ item }}
      with_items: npm_packages
