---
- hosts: workstation
  connection: local

  roles:
    - define_system
    - workstation_add_bin

# OS X
- hosts: sys_Darwin
  connection: local
  gather_facts: false
  roles:
    - workstation_darwin_tasks

# Linux
- hosts: sys_Linux
  connection: local
  gather_facts: false
  roles:
    - workstation_linux_tasks

# Global
- hosts: workstation
  connection: local
  gather_facts: false
  roles:
    - workstation_global_tasks
