---
- hosts: workstation

  vars:
    linux_libraries:
      - git-core
      - ruby-full
      - nodejs
      - docker.io
    debian_libraries:
      - curl
      - nodejs-legacy
    osx_libraries:
      - git
      - node
      - brew-cask
    osx_taps:
      - caskroom/cask
    osx_casks:
      - boot2docker
    npm_packages:
      - grunt-cli
      - grunt
      - bower

  tasks:
    # Debian only
    - name: Install Debian specific libraries
      apt: name={{ item }} state=latest
      with_items: debian_libraries
      when: ansible_distribution == 'Debian'

    # Linux only
    - name: Add nodesource repo
      shell: curl -sL https://deb.nodesource.com/setup | sudo bash -
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Install libraries with apt
      apt: name={{ item }} state=latest
      with_items: linux_libraries
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install libraries with yum
      yum: name={{ item }} state=latest
      with_items: linux_libraries
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    # OS X only
    - name: Update homebrew
      homebrew: update_homebrew=yes upgrade_all=yes
      when: ansible_distribution == 'MacOSX'

    - name: Install homebrew taps
      homebrew_tap: name={{ item }} state=present
      with_items: osx_taps
      when: ansible_distribution == 'MacOSX'

    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items: osx_libraries
      when: ansible_distribution == 'MacOSX'

    - name: Install homebrew casks
      homebrew_cask: name={{ item }} state=present
      with_items: osx_casks
      when: ansible_distribution == 'MacOSX'

    # All systems
    - name: Install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer

    - name: Rename composer.phar to composer
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

    - name: Make composer executable
      file: path=/usr/local/bin/composer mode=a+x state=file

    - name: Install Sass
      action: command sudo gem install sass creates=/usr/local/bin/sass

    - name: Install npm packages globally
      npm: global=yes name={{ item }}
      with_items: npm_packages
